<!-- Navigation Menu -->
<header class="topnav">
    <a href="/en" id="logo-name">
        <img src="img/logo_name_multimedia.png" width="130px" height="auto" alt="Multimédia Logo"><span class="screenreader">Multimédia</span></img>
    </a>
    <nav id="myLinks">
        <a id="aHome" href="/en">home page</a>
        <a id="aMirandela" href="#about">mirandela</a>
        <a id="aEsact" href="/en/esact">esact</a>
        <a id="aCourse" href="#news">course</a>
        <a id="aTeachers" href="#news">teachers</a>
        <a id="aPortfolio" href="#news">portfólio</a>
        <a id="aTestimonials" href="#news">testimonials</a>
        <a id="aStudents" href="#news">core students</a>
        <a id="aErasmus" href="#news">erasmus</a>
        <a id="aContacts"="#contact">contacts</a>
        <a href="<?= $translate ?>">PT | <span class="selected">EN</span></a>
    </nav>
    
    <a href="javascript:void(0);" class="icon" onclick="menuMobile()">
        <!--<i class="fa fa-bars"></i>-->
        <div id="nav-icon">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
    </a>
</header>