<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="robots" content="noindex"> <!-- Atualizar sitemap -->
    
<!-- Responsáveis, para csao de necessidade de futura consulta -->
<meta name="author" content="Carlos Casimiro da Costa"> <!--Supervisor, v1.0 -->
<meta name="author" content="Andreia Maria Camelo Pacheco"> <!-- Interface Designer, v1.0 -->
<meta name="author" content="Ana Teresa Pereira Bessa"> <!-- Interface Designer, v1.0 -->
<meta name="author" content="André Silva Moreira"> <!-- Web Developer, v1.0 -->
        
<meta name="description" content="Website da Licenciatura Multimédia da EsACT-IPB / Multimedia Degree Website at EsACT-IPB">
<meta name="keywords" content="Degree, University, Erasmus, Licenciatura, Curso, Ensino Superior, Multimédia, MM, EsACT, IPB, Insitituto Politécnico de Bragança, Escola Superior de Comunicação Administração e Turismo, Portugal, Bragança, Mirandela, Design, Video, Animação, Áudio, Programação, Desenvolvimento Web, Áudio-Visual">

<meta property="og:title" content="Página Inicial"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://www.imdb.com/title/tt0117500/"/> <!-- Mudar para link website-->
<meta property="og:image" content="https://ia.media-imdb.com/images/rock.jpg"/> <!-- mudar para logo -->
<meta property="og:description " content="Website da Licenciatura Multimédia da EsACT-IPB / Multimedia Degree Website at EsACT-IPB"/>
<meta property="og:determiner" content="">
<meta property="og:locale" content="pt_PT">
<meta property="og:site_name" content="Multimédia | EsACT-IPB">
<meta property="og:video" content=""> <!-- colocar video -->
<meta name="twitter:card" content="summary"></meta> <!-- Incompleto ainda, criar twitter para multimedia?-->

<!--  Perfis sociais/Info  -->
<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "Licenciatura Multimédia",
        "url": "Atualizar com link do site",
        "sameAs": [
            "https://www.facebook.com/nucleomultimedia.mirandela",
            "https://www.instagram.com/nucleomultimedia19.20",
            "https://www.facebook.com/groups/MultimediaEsACT"
        ],
            "address": {
            "@type": "PostalAddress",
            "streetAddress": "Campus do Cruzeiro, Av. 25 de Abril Lote 2",
            "addressRegion": "Mirandela",
            "postalCode": "5370-202",
            "addressCountry": "PT"
        }          
    }
 </script>
 <!--  Perguntas que aparecem nno motor de busca  -->
  <script type="application/ld+json"> 
    {
        "@context": "https://schema.org",
        "@type": "FAQPage",
            "mainEntity": [{
                "@type": "Question",
                "name": "Qual o preço das proprinas?/What is the price of tuition fees?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "<p>Atualmente, no ano letivo 2020/2021 as proprinas são de 69,70€ por mês, totalizando 697,00€ por ano, para mais informações podes consultar <a href="http://portal3.ipb.pt/index.php/pt/"/>aqui</a>.<br>Currently, in the academic year 2020/2021 the fees are € 69.70 per month, totaling € 697.00 per year, for more information you can consult <a href="http://portal3.ipb.pt/index.php/en/"/>here</a>.</p>"
                }
            }, {
                "@type": "Question",
                "name": "Quem consultar para dúvidas mais especificas?/Who to consult for more specific questions?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "<p>Se tiveres dúvidas que este site não te consiga responder podes comunicar com o <a href="http://portal3.ipb.pt/index.php/pt/sa/contactos"/>IPB</a> diretamente, ou com o <a href="https://www.facebook.com/nucleomultimedia.mirandela"/>Núcleo de Estudantes de Multimédia</a>.<br>If you have doubts that this site cannot answer you can communicate with <a href="http://portal3.ipb.pt/index.php/en/sa/contactos"/>IPB</a> directly, or with the <a href="https://www.facebook.com/nucleomultimedia.mirandela"/>Multimedia Students Council</a>.</p>"
                }
              }, {
                "@type": "Question",
                "name": "What is the policy for late/non-delivery of items ordered online?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "Our local teams work diligently to make sure that your order arrives on time, within our normaldelivery hours of 9AM to 8PM in the recipient's time zone. During  busy holiday periods like Christmas, Valentine's and Mother's Day, we may extend our delivery hours before 9AM and after 8PM to ensure that all gifts are delivered on time. If for any reason your gift does not arrive on time, our dedicated Customer Service agents will do everything they can to help successfully resolve your issue. <br/> <p><a href=https://example.com/orders/>Click here</a> to complete the form with your order-related question(s).</p>"
                }
              }, {
                "@type": "Question",
                "name": "When will my credit card be charged?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "We'll attempt to securely charge your credit card at the point of purchase online. If there's a problem, you'll be notified on the spot and prompted to use another card. Once we receive verification of sufficient funds, your payment will be completed and transferred securely to us. Your account will be charged in 24 to 48 hours."
                }
              }, {
                "@type": "Question",
                "name": "Will I be charged sales tax for online orders?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text":"Local and State sales tax will be collected if your recipient's mailing address is in: <ul><li>Arizona</li><li>California</li><li>Colorado</li></ul>"}
                }]
            }
</script>

<link rel="apple-touch-icon" sizes="180x180" href="img/icon/icon_180x180.png">
<link rel="icon" type="image/png" sizes="32x32" href="img/icon/icon_32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="img/icon/icon_16x16.png">

<link rel="stylesheet" type="text/css" href="css/normalize.min.css"> <!-- Não apagar, alterar apenas se para atualizar versões-->
<!--[if IE]>
    <script src="js/html5shiv.min.js"> </script>
<![endif]-->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css">
<link rel="stylesheet" type="text/css" href="font/fonts.min.css">
<link rel="stylesheet" type="text/css" href="css/style.min.css">

<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<script type="text/javascript" src="js/functions.min.js"></script>


