<footer>
    <div id="logos">
        <div>
            <a href="/" hreflang="pt">
                <img src="img/logo_white_multimedia.png" alt="Logo Multimédia" width="48px" height="auto">
            </a>
        </div>
        <div>
            <a href="http://portal3.ipb.pt/index.php/pt/" target="_blank" hreflang="pt">
                <img src="img/logo_white_ipb.png" alt="Logo IPB" width="149px" height="auto">
            </a>
        </div>
    </div>

    <div id="contact">
        <h2>Contacte-nos</h2>

        <h3>EsACT - IPB</h3>
        <p>
            <a href="https://g.page/esactipb?share" target="_blank">
            Campus do Cruzeiro, Avenida 25 de Abril, 
            Cruzeiro, Lote 2. Apartado 128, 5370-202 MIRANDELA</a> <br>
            E-mail:  <a href="mailto: esact@ipb.pt" target="_blank">esact@ipb.pt</a> <br>
            Tel: <a href="tel:278201340" target="_blank">278 201 340</a> / <a href="tel:300029900" target="_blank">300 029 900</a>
        </p>

        <h3>IPB</h3>
        <p>
            <a href="https://goo.gl/maps/iKgZJTV5bCqVohwH9" target="_blank">
            Campus de Santa Apolónia, 5300-253 BRAGANÇA</a> <br>
            E-mail:  <a href="mailto: suporte@ipb.pt" target="_blank">suporte@ipb.pt</a> <br>
            Tel: <a href="tel:+351273303200" target="_blank">(+351) 273 303 200</a> / <a href="tel:+351273331570" target="_blank">(+351) 273 331 570</a> <br>
            Fax: <a href="fax:+351273325405" target="_blank">(+351) 273 325 405</a>
        </p>
    </div>

    <div id="network">
        <a href="https://www.facebook.com/nucleomultimedia.mirandela" target="_blank">
            <img src="img/network/fb_white.png" alt="Icon Facebook" ><span class="screenreader">Facebook</span></img>
        </a>
        <a href="https://www.instagram.com/nucleomultimedia19.20/" target="_blank">
            <img src="img/network/in_white.png" alt="Icon Instagram" ><span class="screenreader">Instagram</span></img>
        </a>
        <a href="" target="_blank">
            <img src="img/network/li_white.png" alt="Icon Linkedin" ><span class="screenreader">Linkedin</span></img>
        </a>
    </div>

    <div id="extra-info" class="flex-space-around"> 
        <div>
            TERMOS DE USO
        </div>
        <div>
            &copy; 2020 IPB - EsACT
        </div>
    </div>
</footer>