<!-- Navigation Menu -->
<header class="topnav" id="topnav">
    <a href="/" id="logo-name">
        <img src="img/logo_name_multimedia.png" width="130px" height="auto" alt="Multimédia Logo"><span class="screenreader">Multimédia</span></img>
    </a>
    <nav id="myLinks">
        <a id="aHome" href="/">página inicial</a>
        <a id="aMirandela" href="#about">mirandela</a>
        <a id="aEsact" href="/esact">esact</a>
        <a id="aCourse" href="#news">curso</a>
        <a id="aTeachers" href="#news">professores</a>
        <a id="aPortfolio" href="#news">portfólio</a>
        <a id="aTestimonials" href="#news">testemunhos</a>
        <a id="aStudents" href="#news">núcleo estudantes</a>
        <a id="aErasmus" href="#news">erasmus</a>
        <a id="aContacts"="#contact">contactos</a>
        <a href="<?= $translate ?>"><span class="selected">PT</span> | EN</a>
    </nav>
    
    <a href="javascript:void(0);" class="icon" onclick="menuMobile()">
        <!--<i class="fa fa-bars"></i>-->
        <div id="nav-icon">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
    </a>
</header>

<div id="toTopBar">
    <a href="#">
        Voltar ao topo <span class='fas fa-angle-up' style="font-size: 14px"></span>
    </a>
</div>